// Generated by Bisonc++ V4.13.01 on Wed, 18 Apr 2018 23:39:11 +0200

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {297, 3}, // 1: start ->  prog_decl data_decl statements
     {300, 0}, // 2: statements ->  <empty>
     {300, 2}, // 3: statements ->  statement statements
     {302, 2}, // 4: statements_plus ->  statement statements
     {298, 3}, // 5: prog_decl (PROGRAM) ->  PROGRAM VARIABLE STMT_DOT
     {299, 0}, // 6: data_decl ->  <empty>
     {299, 3}, // 7: data_decl (DATA) ->  DATA STMT_OPN var_lines
     {303, 2}, // 8: var_lines ->  var_line var_lines
     {303, 1}, // 9: var_lines ->  var_last_line
     {306, 3}, // 10: var_line_core (VARIABLE) ->  VARIABLE TYPE types
     {304, 2}, // 11: var_line (STMT_COMMA) ->  var_line_core STMT_COMMA
     {305, 2}, // 12: var_last_line (STMT_DOT) ->  var_line_core STMT_DOT
     {307, 1}, // 13: types (TYPE_INTEGER) ->  TYPE_INTEGER
     {307, 1}, // 14: types (TYPE_BOOLEAN) ->  TYPE_BOOLEAN
     {301, 1}, // 15: statement ->  statement_move
     {301, 1}, // 16: statement ->  statement_read
     {301, 1}, // 17: statement ->  statement_write
     {301, 1}, // 18: statement ->  statement_math_add
     {301, 1}, // 19: statement ->  statement_math_sub
     {301, 1}, // 20: statement ->  statement_math_mult
     {301, 1}, // 21: statement ->  statement_math_div
     {301, 1}, // 22: statement ->  struct_while
     {301, 1}, // 23: statement ->  struct_if
     {308, 4}, // 24: statement_move (OP_MOVE) ->  OP_MOVE expression to_var STMT_DOT
     {309, 3}, // 25: statement_read (OP_READ) ->  OP_READ to_var STMT_DOT
     {310, 3}, // 26: statement_write (OP_WRITE) ->  OP_WRITE expression STMT_DOT
     {311, 4}, // 27: statement_math_add (OP_ADD) ->  OP_ADD expression to_var STMT_DOT
     {312, 5}, // 28: statement_math_sub (MATH_SUB) ->  MATH_SUB expression DIR_FROM VARIABLE STMT_DOT
     {313, 5}, // 29: statement_math_mult (MATH_MULT) ->  MATH_MULT VARIABLE DIR_BY expression STMT_DOT
     {314, 5}, // 30: statement_math_div (MATH_DIV) ->  MATH_DIV VARIABLE DIR_BY expression STMT_DOT
     {317, 2}, // 31: to_var (DIR_TO) ->  DIR_TO VARIABLE
     {315, 6}, // 32: struct_while (STRUCT_WHILE) ->  STRUCT_WHILE VARIABLE STMT_DOT statements STRUCT_ENDWHILE STMT_DOT
     {316, 5}, // 33: struct_if (STRUCT_IF) ->  STRUCT_IF logic_body if_body STRUCT_ENDIF STMT_DOT
     {318, 3}, // 34: logic_body (STMT_DOT) ->  expression STMT_DOT statements_plus
     {319, 0}, // 35: if_body ->  <empty>
     {319, 1}, // 36: if_body ->  if_else
     {319, 1}, // 37: if_body ->  if_elseif
     {320, 3}, // 38: if_else (STRUCT_ELSE) ->  STRUCT_ELSE STMT_DOT statements
     {321, 3}, // 39: if_elseif (STRUCT_ELSEIF) ->  STRUCT_ELSEIF logic_body if_elseif
     {321, 2}, // 40: if_elseif (STRUCT_ELSEIF) ->  STRUCT_ELSEIF logic_body
     {321, 3}, // 41: if_elseif (STRUCT_ELSEIF) ->  STRUCT_ELSEIF logic_body if_else
     {322, 1}, // 42: expression (VARIABLE) ->  VARIABLE
     {322, 1}, // 43: expression (NUMBER) ->  NUMBER
     {322, 1}, // 44: expression ->  literal_boolean
     {322, 3}, // 45: expression (PAR_OPN) ->  PAR_OPN expression PAR_CLS
     {322, 2}, // 46: expression (LOGIC_NOT) ->  LOGIC_NOT expression
     {322, 3}, // 47: expression (LOGIC_AND) ->  expression LOGIC_AND expression
     {322, 3}, // 48: expression (LOGIC_OR) ->  expression LOGIC_OR expression
     {322, 3}, // 49: expression (COMP_LS) ->  expression COMP_LS expression
     {322, 3}, // 50: expression (COMP_GT) ->  expression COMP_GT expression
     {322, 3}, // 51: expression (COMP_EQ) ->  expression COMP_EQ expression
     {323, 1}, // 52: literal_boolean (BOOLEAN_FALSE) ->  BOOLEAN_FALSE
     {323, 1}, // 53: literal_boolean (BOOLEAN_TRUE) ->  BOOLEAN_TRUE
     {324, 1}, // 54: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 4} },             
    { {       297}, { 1} }, // start    
    { {       298}, { 2} }, // prog_decl
    { {       260}, { 3} }, // PROGRAM  
    { {         0}, { 0} },             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {  3} },             
    { {     299}, {  4} }, // data_decl
    { {     261}, {  5} }, // DATA     
    { {       0}, { -6} },             
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 2} },            
    { {       291}, { 6} }, // VARIABLE
    { {         0}, { 0} },            
};

SR__ s_4[] =
{
    { { REQ_DEF}, { 21} },                       
    { {     300}, {  7} }, // statements         
    { {     301}, {  8} }, // statement          
    { {     308}, {  9} }, // statement_move     
    { {     309}, { 10} }, // statement_read     
    { {     310}, { 11} }, // statement_write    
    { {     311}, { 12} }, // statement_math_add 
    { {     312}, { 13} }, // statement_math_sub 
    { {     313}, { 14} }, // statement_math_mult
    { {     314}, { 15} }, // statement_math_div 
    { {     315}, { 16} }, // struct_while       
    { {     316}, { 17} }, // struct_if          
    { {     265}, { 18} }, // OP_MOVE            
    { {     266}, { 19} }, // OP_READ            
    { {     268}, { 20} }, // OP_WRITE           
    { {     267}, { 21} }, // OP_ADD             
    { {     285}, { 22} }, // MATH_SUB           
    { {     286}, { 23} }, // MATH_MULT          
    { {     287}, { 24} }, // MATH_DIV           
    { {     273}, { 25} }, // STRUCT_WHILE       
    { {     272}, { 26} }, // STRUCT_IF          
    { {       0}, { -2} },                       
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       259}, { 27} }, // STMT_OPN
    { {         0}, {  0} },            
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 28} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_7[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_8[] =
{
    { { REQ_DEF}, { 21} },                       
    { {     300}, { 29} }, // statements         
    { {     301}, {  8} }, // statement          
    { {     308}, {  9} }, // statement_move     
    { {     309}, { 10} }, // statement_read     
    { {     310}, { 11} }, // statement_write    
    { {     311}, { 12} }, // statement_math_add 
    { {     312}, { 13} }, // statement_math_sub 
    { {     313}, { 14} }, // statement_math_mult
    { {     314}, { 15} }, // statement_math_div 
    { {     315}, { 16} }, // struct_while       
    { {     316}, { 17} }, // struct_if          
    { {     265}, { 18} }, // OP_MOVE            
    { {     266}, { 19} }, // OP_READ            
    { {     268}, { 20} }, // OP_WRITE           
    { {     267}, { 21} }, // OP_ADD             
    { {     285}, { 22} }, // MATH_SUB           
    { {     286}, { 23} }, // MATH_MULT          
    { {     287}, { 24} }, // MATH_DIV           
    { {     273}, { 25} }, // STRUCT_WHILE       
    { {     272}, { 26} }, // STRUCT_IF          
    { {       0}, { -2} },                       
};

SR__ s_9[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_10[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_12[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 30} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       317}, { 38} }, // to_var
    { {       269}, { 39} }, // DIR_TO
    { {         0}, {  0} },          
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 40} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 41} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 42} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       291}, { 43} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       291}, { 44} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       291}, { 45} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, { 10} },                   
    { {       318}, { 46} }, // logic_body     
    { {       322}, { 47} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  6} },                 
    { {       303}, { 48} }, // var_lines    
    { {       304}, { 49} }, // var_line     
    { {       305}, { 50} }, // var_last_line
    { {       306}, { 51} }, // var_line_core
    { {       291}, { 52} }, // VARIABLE     
    { {         0}, {  0} },                 
};

SR__ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       317}, { 53} }, // to_var   
    { {       280}, { 54} }, // LOGIC_AND
    { {       281}, { 55} }, // LOGIC_OR 
    { {       283}, { 56} }, // COMP_LS  
    { {       284}, { 57} }, // COMP_GT  
    { {       282}, { 58} }, // COMP_EQ  
    { {       269}, { 39} }, // DIR_TO   
    { {         0}, {  0} },             
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 59} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 60} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 61} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       291}, { 62} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  7} },             
    { {       257}, { 63} }, // STMT_DOT 
    { {       280}, { 54} }, // LOGIC_AND
    { {       281}, { 55} }, // LOGIC_OR 
    { {       283}, { 56} }, // COMP_LS  
    { {       284}, { 57} }, // COMP_GT  
    { {       282}, { 58} }, // COMP_EQ  
    { {         0}, {  0} },             
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  8} },             
    { {       317}, { 64} }, // to_var   
    { {       280}, { 54} }, // LOGIC_AND
    { {       281}, { 55} }, // LOGIC_OR 
    { {       283}, { 56} }, // COMP_LS  
    { {       284}, { 57} }, // COMP_GT  
    { {       282}, { 58} }, // COMP_EQ  
    { {       269}, { 39} }, // DIR_TO   
    { {         0}, {  0} },             
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  7} },             
    { {       271}, { 65} }, // DIR_FROM 
    { {       280}, { 54} }, // LOGIC_AND
    { {       281}, { 55} }, // LOGIC_OR 
    { {       283}, { 56} }, // COMP_LS  
    { {       284}, { 57} }, // COMP_GT  
    { {       282}, { 58} }, // COMP_EQ  
    { {         0}, {  0} },             
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       270}, { 66} }, // DIR_BY
    { {         0}, {  0} },          
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       270}, { 67} }, // DIR_BY
    { {         0}, {  0} },          
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 68} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_46[] =
{
    { { REQ_DEF}, {   6} },                 
    { {     319}, {  69} }, // if_body      
    { {     320}, {  70} }, // if_else      
    { {     321}, {  71} }, // if_elseif    
    { {     274}, {  72} }, // STRUCT_ELSE  
    { {     275}, {  73} }, // STRUCT_ELSEIF
    { {       0}, { -35} },                 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  7} },             
    { {       257}, { 74} }, // STMT_DOT 
    { {       280}, { 54} }, // LOGIC_AND
    { {       281}, { 55} }, // LOGIC_OR 
    { {       283}, { 56} }, // COMP_LS  
    { {       284}, { 57} }, // COMP_GT  
    { {       282}, { 58} }, // COMP_EQ  
    { {         0}, {  0} },             
};

SR__ s_48[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  6} },                 
    { {       303}, { 75} }, // var_lines    
    { {       304}, { 49} }, // var_line     
    { {       305}, { 50} }, // var_last_line
    { {       306}, { 51} }, // var_line_core
    { {       291}, { 52} }, // VARIABLE     
    { {         0}, {  0} },                 
};

SR__ s_50[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       258}, { 76} }, // STMT_COMMA
    { {       257}, { 77} }, // STMT_DOT  
    { {         0}, {  0} },              
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       262}, { 78} }, // TYPE
    { {         0}, {  0} },        
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 79} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 80} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 81} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 82} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 83} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 84} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  7} },             
    { {       279}, { 85} }, // PAR_CLS  
    { {       280}, { 54} }, // LOGIC_AND
    { {       281}, { 55} }, // LOGIC_OR 
    { {       283}, { 56} }, // COMP_LS  
    { {       284}, { 57} }, // COMP_GT  
    { {       282}, { 58} }, // COMP_EQ  
    { {         0}, {  0} },             
};

SR__ s_60[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 86} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       291}, { 87} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 88} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  9} },                   
    { {       322}, { 89} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_68[] =
{
    { { REQ_DEF}, { 21} },                       
    { {     300}, { 90} }, // statements         
    { {     301}, {  8} }, // statement          
    { {     308}, {  9} }, // statement_move     
    { {     309}, { 10} }, // statement_read     
    { {     310}, { 11} }, // statement_write    
    { {     311}, { 12} }, // statement_math_add 
    { {     312}, { 13} }, // statement_math_sub 
    { {     313}, { 14} }, // statement_math_mult
    { {     314}, { 15} }, // statement_math_div 
    { {     315}, { 16} }, // struct_while       
    { {     316}, { 17} }, // struct_if          
    { {     265}, { 18} }, // OP_MOVE            
    { {     266}, { 19} }, // OP_READ            
    { {     268}, { 20} }, // OP_WRITE           
    { {     267}, { 21} }, // OP_ADD             
    { {     285}, { 22} }, // MATH_SUB           
    { {     286}, { 23} }, // MATH_MULT          
    { {     287}, { 24} }, // MATH_DIV           
    { {     273}, { 25} }, // STRUCT_WHILE       
    { {     272}, { 26} }, // STRUCT_IF          
    { {       0}, { -2} },                       
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       276}, { 91} }, // STRUCT_ENDIF
    { {         0}, {  0} },                
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_71[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 92} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 10} },                   
    { {       318}, { 93} }, // logic_body     
    { {       322}, { 47} }, // expression     
    { {       291}, { 31} }, // VARIABLE       
    { {       292}, { 32} }, // NUMBER         
    { {       323}, { 33} }, // literal_boolean
    { {       278}, { 34} }, // PAR_OPN        
    { {       288}, { 35} }, // LOGIC_NOT      
    { {       290}, { 36} }, // BOOLEAN_FALSE  
    { {       289}, { 37} }, // BOOLEAN_TRUE   
    { {         0}, {  0} },                   
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, { 21} },                       
    { {       302}, { 94} }, // statements_plus    
    { {       301}, { 95} }, // statement          
    { {       308}, {  9} }, // statement_move     
    { {       309}, { 10} }, // statement_read     
    { {       310}, { 11} }, // statement_write    
    { {       311}, { 12} }, // statement_math_add 
    { {       312}, { 13} }, // statement_math_sub 
    { {       313}, { 14} }, // statement_math_mult
    { {       314}, { 15} }, // statement_math_div 
    { {       315}, { 16} }, // struct_while       
    { {       316}, { 17} }, // struct_if          
    { {       265}, { 18} }, // OP_MOVE            
    { {       266}, { 19} }, // OP_READ            
    { {       268}, { 20} }, // OP_WRITE           
    { {       267}, { 21} }, // OP_ADD             
    { {       285}, { 22} }, // MATH_SUB           
    { {       286}, { 23} }, // MATH_MULT          
    { {       287}, { 24} }, // MATH_DIV           
    { {       273}, { 25} }, // STRUCT_WHILE       
    { {       272}, { 26} }, // STRUCT_IF          
    { {         0}, {  0} },                       
};

SR__ s_75[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  4} },                
    { {       307}, { 96} }, // types       
    { {       263}, { 97} }, // TYPE_INTEGER
    { {       264}, { 98} }, // TYPE_BOOLEAN
    { {         0}, {  0} },                
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_80[] =
{
    { { REQ_DEF}, {   4} },           
    { {     283}, {  56} }, // COMP_LS
    { {     284}, {  57} }, // COMP_GT
    { {     282}, {  58} }, // COMP_EQ
    { {       0}, { -47} },           
};

SR__ s_81[] =
{
    { { REQ_DEF}, {   4} },           
    { {     283}, {  56} }, // COMP_LS
    { {     284}, {  57} }, // COMP_GT
    { {     282}, {  58} }, // COMP_EQ
    { {       0}, { -48} },           
};

SR__ s_82[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_83[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_84[] =
{
    { { REQ_DEF}, {   3} },           
    { {     283}, {  56} }, // COMP_LS
    { {     284}, {  57} }, // COMP_GT
    { {       0}, { -51} },           
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 99} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {   7} },             
    { {       257}, { 100} }, // STMT_DOT 
    { {       280}, {  54} }, // LOGIC_AND
    { {       281}, {  55} }, // LOGIC_OR 
    { {       283}, {  56} }, // COMP_LS  
    { {       284}, {  57} }, // COMP_GT  
    { {       282}, {  58} }, // COMP_EQ  
    { {         0}, {   0} },             
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {   7} },             
    { {       257}, { 101} }, // STMT_DOT 
    { {       280}, {  54} }, // LOGIC_AND
    { {       281}, {  55} }, // LOGIC_OR 
    { {       283}, {  56} }, // COMP_LS  
    { {       284}, {  57} }, // COMP_GT  
    { {       282}, {  58} }, // COMP_EQ  
    { {         0}, {   0} },             
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {   2} },                   
    { {       277}, { 102} }, // STRUCT_ENDWHILE
    { {         0}, {   0} },                   
};

SR__ s_91[] =
{
    { { REQ_TOKEN}, {   2} },            
    { {       257}, { 103} }, // STMT_DOT
    { {         0}, {   0} },            
};

SR__ s_92[] =
{
    { { REQ_DEF}, {  21} },                       
    { {     300}, { 104} }, // statements         
    { {     301}, {   8} }, // statement          
    { {     308}, {   9} }, // statement_move     
    { {     309}, {  10} }, // statement_read     
    { {     310}, {  11} }, // statement_write    
    { {     311}, {  12} }, // statement_math_add 
    { {     312}, {  13} }, // statement_math_sub 
    { {     313}, {  14} }, // statement_math_mult
    { {     314}, {  15} }, // statement_math_div 
    { {     315}, {  16} }, // struct_while       
    { {     316}, {  17} }, // struct_if          
    { {     265}, {  18} }, // OP_MOVE            
    { {     266}, {  19} }, // OP_READ            
    { {     268}, {  20} }, // OP_WRITE           
    { {     267}, {  21} }, // OP_ADD             
    { {     285}, {  22} }, // MATH_SUB           
    { {     286}, {  23} }, // MATH_MULT          
    { {     287}, {  24} }, // MATH_DIV           
    { {     273}, {  25} }, // STRUCT_WHILE       
    { {     272}, {  26} }, // STRUCT_IF          
    { {       0}, {  -2} },                       
};

SR__ s_93[] =
{
    { { REQ_DEF}, {   5} },                 
    { {     321}, { 105} }, // if_elseif    
    { {     320}, { 106} }, // if_else      
    { {     275}, {  73} }, // STRUCT_ELSEIF
    { {     274}, {  72} }, // STRUCT_ELSE  
    { {       0}, { -40} },                 
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_95[] =
{
    { { REQ_DEF}, {  21} },                       
    { {     300}, { 107} }, // statements         
    { {     301}, {   8} }, // statement          
    { {     308}, {   9} }, // statement_move     
    { {     309}, {  10} }, // statement_read     
    { {     310}, {  11} }, // statement_write    
    { {     311}, {  12} }, // statement_math_add 
    { {     312}, {  13} }, // statement_math_sub 
    { {     313}, {  14} }, // statement_math_mult
    { {     314}, {  15} }, // statement_math_div 
    { {     315}, {  16} }, // struct_while       
    { {     316}, {  17} }, // struct_if          
    { {     265}, {  18} }, // OP_MOVE            
    { {     266}, {  19} }, // OP_READ            
    { {     268}, {  20} }, // OP_WRITE           
    { {     267}, {  21} }, // OP_ADD             
    { {     285}, {  22} }, // MATH_SUB           
    { {     286}, {  23} }, // MATH_MULT          
    { {     287}, {  24} }, // MATH_DIV           
    { {     273}, {  25} }, // STRUCT_WHILE       
    { {     272}, {  26} }, // STRUCT_IF          
    { {       0}, {  -2} },                       
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_99[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_101[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {   2} },            
    { {       257}, { 108} }, // STMT_DOT
    { {         0}, {   0} },            
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_104[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_107[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

// $insert defaultactionreturn
                            // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 58 "abaps.y"
        {
         std::cout << "start -> prog_decl data_decl statements" << std::endl;
         }
        break;

        case 2:
#line 65 "abaps.y"
        {
         std::cout << "statements -> null" << std::endl;
         }
        break;

        case 3:
#line 69 "abaps.y"
        {
         std::cout << "statements -> statement statements" << std::endl;
         }
        break;

        case 4:
#line 75 "abaps.y"
        {
         std::cout << "statements_plus -> statement statements" << std::endl;
         }
        break;

        case 5:
#line 81 "abaps.y"
        {
         std::cout << "prog_decl -> PROGRAM VARIABLE STMT_DOT" << std::endl;
         }
        break;

        case 6:
#line 88 "abaps.y"
        {
         std::cout << "data_decl -> null" << std::endl;
         }
        break;

        case 7:
#line 92 "abaps.y"
        {
         std::cout << "data_decl -> DATA_STMT_OPN var_lines" << std::endl;
         }
        break;

        case 8:
#line 98 "abaps.y"
        {
         std::cout << "var_lines -> var_line var_lines" << std::endl;
         }
        break;

        case 9:
#line 102 "abaps.y"
        {
         std::cout << "var_line -> var_last_line" << std::endl;
         }
        break;

        case 10:
#line 108 "abaps.y"
        {
         if (symbols.count(*d_vsp__[-2].value) > 0) {
         std::stringstream ss;
         ss << "Already declared variable: \"" << *d_vsp__[-2].value << "\", Previous declaration: " 
         << symbols[*d_vsp__[-2].value].row;
         error(ss.str().c_str());
         }
         
         symbols[*d_vsp__[-2].value] = VarData(d_loc__.first_line, *d_vsp__[0].type);
         std::cout << "var_line -> VARIABLE (" << symbols[*d_vsp__[-2].value] << ") TYPE TYPE_INTEGER" << std::endl;
         }
        break;

        case 11:
#line 123 "abaps.y"
        {
         std::cout << "var_line -> var_line_core STMT_COMMA" << std::endl;
         }
        break;

        case 12:
#line 129 "abaps.y"
        {
         std::cout << "var_last_line -> var_line_core STMT_DOT" << std::endl;
         }
        break;

        case 13:
#line 135 "abaps.y"
        {
         std::cout << "types -> TYPE_INTEGER" << std::endl;
         d_val__.type = new Type(Integer);
         }
        break;

        case 14:
#line 140 "abaps.y"
        {
         std::cout << "types -> TYPE_BOOLEAN" << std::endl;
         d_val__.type = new Type(Boolean);
         }
        break;

        case 15:
#line 147 "abaps.y"
        {
         std::cout << "statement -> statement_move" << std::endl;
         }
        break;

        case 16:
#line 151 "abaps.y"
        {
         std::cout << "statement -> statement_read" << std::endl;
         }
        break;

        case 17:
#line 155 "abaps.y"
        {
         std::cout << "statement -> statement_write" << std::endl;
         }
        break;

        case 18:
#line 159 "abaps.y"
        {
         std::cout << "statement -> statement_math_add" << std::endl;
         }
        break;

        case 19:
#line 163 "abaps.y"
        {
         std::cout << "statement -> statement_math_sub" << std::endl;
         }
        break;

        case 20:
#line 167 "abaps.y"
        {
         std::cout << "statement -> statement_math_mult" << std::endl;
         }
        break;

        case 21:
#line 171 "abaps.y"
        {
         std::cout << "statement -> statement_math_div" << std::endl;
         }
        break;

        case 22:
#line 175 "abaps.y"
        {
         std::cout << "statement -> struct_while" << std::endl;
         }
        break;

        case 23:
#line 179 "abaps.y"
        {
         std::cout << "statement -> struct_if" << std::endl;
         }
        break;

        case 24:
#line 185 "abaps.y"
        {
         std::cout << "statement_move -> OP_MOVE expression to_var STMT_DOT" << std::endl;
         if(*d_vsp__[-2].type != *d_vsp__[-1].type) {
         std::stringstream ss;
         ss << "Both end needs to have the same types. Got instead from: \"" << typeNames[*d_vsp__[-2].type] << "\" to: " << typeNames[*d_vsp__[-1].type];
         error(ss.str().c_str());
         }
         }
        break;

        case 25:
#line 197 "abaps.y"
        {
         std::cout << "statement_read -> OP_READ to_var STMT_DOT" << std::endl;
         }
        break;

        case 26:
#line 203 "abaps.y"
        {
         std::cout << "statement_write -> OP_WRITE expression STMT_DOT" << std::endl;
         }
        break;

        case 27:
#line 209 "abaps.y"
        {
         std::cout << "statement_math_add -> OP_ADD expression to_var STMT_DOT" << std::endl;
         if(*d_vsp__[-2].type != Integer) {
         std::stringstream ss;
         ss << "Math add needs numerical value. \"" << *d_vsp__[-2].type << "\" got " << typeNames[*d_vsp__[-2].type] << " instead of Integer.";
         std::cout << ss.str() << std::endl;
         error(ss.str().c_str());
         }
         if(*d_vsp__[-1].type != Integer) {
         std::stringstream ss;
         ss << "Math add needs numerical value. \"" << *d_vsp__[-1].type << "\" got " << typeNames[*d_vsp__[-1].type] << " instead of Integer.";
         std::cout << ss.str() << std::endl;
         error(ss.str().c_str());
         }
         }
        break;

        case 28:
#line 229 "abaps.y"
        {
         if (symbols.count(*d_vsp__[-1].value) == 0) {
         std::stringstream ss;
         ss << "Not declared variable: \"" << *d_vsp__[-1].value << "\"";
         error(ss.str().c_str());
         }
         if(*d_vsp__[-3].type != Integer) {
         std::stringstream ss;
         ss << "Math sub needs numerical value. \"" << *d_vsp__[-3].type << "\" got " << typeNames[*d_vsp__[-3].type] << " instead of Integer.";
         error(ss.str().c_str());
         }
         if(symbols[*d_vsp__[-1].value].type != Integer) {
         std::stringstream ss;
         ss << "Math sub needs numerical value. \"" << *d_vsp__[-1].value << "\" got " << typeNames[symbols[*d_vsp__[-1].value].type] << " instead of Integer.";
         error(ss.str().c_str());
         }
         std::cout << "statement_math_sub -> MATH_SUB expression DIR_FROM VARIABLE (" << symbols[*d_vsp__[-1].value] << ") STMT_DOT" << std::endl;
         }
        break;

        case 29:
#line 253 "abaps.y"
        {
         if (symbols.count(*d_vsp__[-3].value) == 0) {
         std::stringstream ss;
         ss << "Not declared variable: \"" << *d_vsp__[-3].value << "\"";
         error(ss.str().c_str());
         }
         if(symbols[*d_vsp__[-3].value].type != Integer) {
         std::stringstream ss;
         ss << "Math mult needs numerical value. \"" << *d_vsp__[-3].value << "\" got " << typeNames[symbols[*d_vsp__[-3].value].type] << " instead of Integer.";
         error(ss.str().c_str());
         }
         if(*d_vsp__[-1].type != Integer) {
         std::stringstream ss;
         ss << "Math mult needs numerical value. \"" << *d_vsp__[-1].type << "\" got " << typeNames[*d_vsp__[-1].type] << " instead of Integer.";
         error(ss.str().c_str());
         }
         std::cout << "statement_math_mult -> MATH_MULT VARIABLE (" << symbols[*d_vsp__[-3].value] << ") DIR_BY expression STMT_DOT" << std::endl;
         }
        break;

        case 30:
#line 277 "abaps.y"
        {
         if (symbols.count(*d_vsp__[-3].value) == 0) {
         std::stringstream ss;
         ss << "Not declared variable: \"" << *d_vsp__[-3].value << "\"";
         error(ss.str().c_str());
         }
         if(symbols[*d_vsp__[-3].value].type != Integer) {
         std::stringstream ss;
         ss << "Math div needs numerical value. \"" << *d_vsp__[-3].value << "\" got " << typeNames[symbols[*d_vsp__[-3].value].type] << " instead of Integer.";
         error(ss.str().c_str());
         }
         if(*d_vsp__[-1].type != Integer) {
         std::stringstream ss;
         ss << "Math div needs numerical value. \"" << *d_vsp__[-1].type << "\" got " << typeNames[*d_vsp__[-1].type] << " instead of Integer.";
         error(ss.str().c_str());
         }
         
         std::cout << "statement_math_div -> MATH_DIV VARIABLE (" << symbols[*d_vsp__[-3].value] << ") DIR_BY expression STMT_DOT" << std::endl;
         }
        break;

        case 31:
#line 301 "abaps.y"
        {
         std::cout << "to_var -> DIR_TO VARIABLE (" << symbols[*d_vsp__[0].value] << ")" << std::endl;
         if (symbols.count(*d_vsp__[0].value) == 0) {
         std::stringstream ss;
         ss << "Not declared variable: \"" << *d_vsp__[0].value << "\"";
         error(ss.str().c_str());
         }
         d_val__.type = new Type(symbols[*d_vsp__[0].value].type);
         }
        break;

        case 32:
#line 315 "abaps.y"
        {
         std::cout << "while -> STRUCT_WHILE statement STMT_DOT statements STRUCT_ENDWHILE STMT_DOT" << std::endl;
         }
        break;

        case 33:
#line 321 "abaps.y"
        {
         std::cout << "struct_if -> STRUCT_IF logic_body if_body STRUCT_ENDIF STMT_DOT" << std::endl;
         }
        break;

        case 34:
#line 327 "abaps.y"
        {
         if(*d_vsp__[-2].type != Boolean) {
         std::stringstream ss;
         ss << "Logic expression needs to be Boolean. \"" << *d_vsp__[-2].type << "\" got " << typeNames[*d_vsp__[-2].type] << " instead of Boolean.";
         error(ss.str().c_str());
         }
         std::cout << "logic_body -> expression STMT_DOT statements_plus" << std::endl;
         }
        break;

        case 35:
#line 340 "abaps.y"
        {
         std::cout << "if_body -> null" << std::endl;
         }
        break;

        case 36:
#line 344 "abaps.y"
        {
         std::cout << "if_body -> if_else" << std::endl;
         }
        break;

        case 37:
#line 348 "abaps.y"
        {
         std::cout << "if_body -> if_elseif" << std::endl;
         }
        break;

        case 38:
#line 354 "abaps.y"
        {
         std::cout << "if_else -> STRUCT_ELSE STMT_DOT statements" << std::endl;
         }
        break;

        case 39:
#line 360 "abaps.y"
        {
         std::cout << "if_elseif -> STRUCT_ELSEIF logic_body if_elseif" << std::endl;
         }
        break;

        case 40:
#line 364 "abaps.y"
        {
         std::cout << "if_elseif -> STRUCT_ELSEIF logic_body" << std::endl;
         }
        break;

        case 41:
#line 368 "abaps.y"
        {
         std::cout << "if_elseif -> STRUCT_ELSEIF logic_body if_else" << std::endl;
         }
        break;

        case 42:
#line 374 "abaps.y"
        {
         if (symbols.count(*d_vsp__[0].value) == 0) {
         std::stringstream ss;
         ss << "Not declared variable: \"" << *d_vsp__[0].value << "\"";
         error(ss.str().c_str());
         }
         std::cout << "expression -> VARIABLE (name: " << symbols[*d_vsp__[0].value] << " type: " << typeNames[symbols[*d_vsp__[0].value].type] << ")" << std::endl;
         d_val__.type = new Type(symbols[*d_vsp__[0].value].type);
         }
        break;

        case 43:
#line 386 "abaps.y"
        {
         std::cout << "expression -> NUMBER" << std::endl;
         d_val__.type = new Type(Integer);
         }
        break;

        case 44:
#line 392 "abaps.y"
        {
         std::cout << "expression -> literal_boolean" << std::endl;
         d_val__.type = new Type(*d_vsp__[0].type);
         }
        break;

        case 45:
#line 397 "abaps.y"
        {
         std::cout << "expression -> PAR_CLS expression (" << typeNames[*d_vsp__[-1].type] << ") PAR_CLS" << std::endl;
         d_val__.type = new Type(*d_vsp__[-1].type);
         }
        break;

        case 46:
#line 402 "abaps.y"
        {
         if(*d_vsp__[0].type != Boolean) {
         std::stringstream ss;
         ss << "Logical expressions needs boolean value. \"" << *d_vsp__[0].type << "\" got " << typeNames[*d_vsp__[0].type] << " instead of Boolean.";
         error(ss.str().c_str());
         }
         std::cout << "expression -> LOGIC_NOT expression (" << typeNames[*d_vsp__[0].type] << ")" << std::endl;
         d_val__.type = new Type(*d_vsp__[0].type);
         }
        break;

        case 47:
#line 414 "abaps.y"
        {
         if(*d_vsp__[-2].type != Boolean) {
         std::stringstream ss;
         ss << "Logical expressions needs boolean value. \"" << *d_vsp__[-2].type << "\" got " << typeNames[*d_vsp__[-2].type] << " instead of Boolean.";
         error(ss.str().c_str());
         }
         if(*d_vsp__[0].type != Boolean) {
         std::stringstream ss;
         ss << "Logical expressions needs boolean value. \"" << *d_vsp__[0].type << "\" got " << typeNames[*d_vsp__[0].type] << " instead of Boolean.";
         error(ss.str().c_str());
         }
         std::cout << "expression -> expression  (" << typeNames[*d_vsp__[-2].type] << ") LOGIC_AND expression  (" << typeNames[*d_vsp__[0].type] << ")" << std::endl;
         d_val__.type = new Type(*d_vsp__[-2].type);
         }
        break;

        case 48:
#line 432 "abaps.y"
        {
         if(*d_vsp__[-2].type != Boolean) {
         std::stringstream ss;
         ss << "Logical expressions needs boolean value. \"" << *d_vsp__[-2].type << "\" got " << typeNames[*d_vsp__[-2].type] << " instead of Boolean.";
         error(ss.str().c_str());
         }
         if(*d_vsp__[0].type != Boolean) {
         std::stringstream ss;
         ss << "Logical expressions needs boolean value. \"" << *d_vsp__[0].type << "\" got " << typeNames[*d_vsp__[0].type] << " instead of Boolean.";
         error(ss.str().c_str());
         }
         std::cout << "expression -> expression  (" << typeNames[*d_vsp__[-2].type] << ") LOGIC_OR expression  (" << typeNames[*d_vsp__[0].type] << ")" << std::endl;
         d_val__.type = new Type(*d_vsp__[-2].type);
         }
        break;

        case 49:
#line 450 "abaps.y"
        {
         if(*d_vsp__[-2].type != Integer) {
         std::stringstream ss;
         ss << "Comparisons needs numerical values. \"" << *d_vsp__[-2].type << "\" got " << typeNames[*d_vsp__[-2].type] << " instead of Integer.";
         error(ss.str().c_str());
         }
         if(*d_vsp__[0].type != Integer) {
         std::stringstream ss;
         ss << "Logical expressions needs boolean value. \"" << *d_vsp__[0].type << "\" got " << typeNames[*d_vsp__[0].type] << " instead of Boolean.";
         error(ss.str().c_str());
         }
         
         std::cout << "expression -> expression (" << typeNames[*d_vsp__[-2].type] << ") LOGIC_OR expression  (" << typeNames[*d_vsp__[0].type] << ")" << std::endl;
         d_val__.type = new Type(Boolean);
         }
        break;

        case 50:
#line 468 "abaps.y"
        {
         if(*d_vsp__[-2].type != Integer) {
         std::stringstream ss;
         ss << "Comparisons needs numerical values. \"" << *d_vsp__[-2].type << "\" got " << typeNames[*d_vsp__[-2].type] << " instead of Integer.";
         error(ss.str().c_str());
         }
         if(*d_vsp__[0].type != Integer) {
         std::stringstream ss;
         ss << "Logical expressions needs boolean value. \"" << *d_vsp__[0].type << "\" got " << typeNames[*d_vsp__[0].type] << " instead of Boolean.";
         error(ss.str().c_str());
         }
         std::cout << "expression -> expression (" << typeNames[*d_vsp__[-2].type] << ") COMP_GT expression  (" << typeNames[*d_vsp__[0].type] << ")" << std::endl;
         d_val__.type = new Type(Boolean);
         }
        break;

        case 51:
#line 485 "abaps.y"
        {
         if(*d_vsp__[-2].type != *d_vsp__[0].type) {
         std::stringstream ss;
         ss << "Equals needs identical expressions. \"" << *d_vsp__[-2].type << "\" got " << typeNames[*d_vsp__[-2].type] << " and \"" << *d_vsp__[0].type << "\" got " << typeNames[*d_vsp__[0].type] << std::endl;
         error(ss.str().c_str());
         }
         std::cout << "expression -> expression (" << typeNames[*d_vsp__[-2].type] << ") COMP_EQ expression  (" << typeNames[*d_vsp__[0].type] << ")" << std::endl;
         d_val__.type = new Type(Boolean);
         }
        break;

        case 52:
#line 499 "abaps.y"
        {
         std::cout << "literal_boolean -> BOOLEAN_FALSE" << std::endl;
         d_val__.type = new Type(Boolean);
         }
        break;

        case 53:
#line 504 "abaps.y"
        {
         std::cout << "literal_boolean -> BOOLEAN_TRUE" << std::endl;
         d_val__.type = new Type(Boolean);
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



