// Generated by Bisonc++ V4.13.01 on Sun, 25 Mar 2018 01:34:36 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {289, 2}, // 1: start ->  prog_decl expressions
     {291, 0}, // 2: expressions ->  <empty>
     {291, 2}, // 3: expressions ->  data_decl expressions
     {291, 2}, // 4: expressions ->  exp expressions
     {294, 2}, // 5: expressions_plus ->  exp expressions
     {290, 3}, // 6: prog_decl (PROGRAM) ->  PROGRAM VARIABLE STMT_DOT
     {292, 3}, // 7: data_decl (DATA) ->  DATA STMT_OPN var_lines
     {295, 2}, // 8: var_lines ->  var_line var_lines
     {295, 1}, // 9: var_lines ->  var_last_line
     {298, 3}, // 10: var_line_core (VARIABLE) ->  VARIABLE TYPE types
     {296, 2}, // 11: var_line (STMT_COMMA) ->  var_line_core STMT_COMMA
     {297, 2}, // 12: var_last_line (STMT_DOT) ->  var_line_core STMT_DOT
     {299, 1}, // 13: types (TYPE_INTEGER) ->  TYPE_INTEGER
     {299, 1}, // 14: types (TYPE_BOOLEAN) ->  TYPE_BOOLEAN
     {293, 4}, // 15: exp (OP_MOVE) ->  OP_MOVE value to_var STMT_DOT
     {293, 3}, // 16: exp (OP_READ) ->  OP_READ to_var STMT_DOT
     {293, 3}, // 17: exp (OP_WRITE) ->  OP_WRITE value STMT_DOT
     {293, 4}, // 18: exp (OP_ADD) ->  OP_ADD value to_var STMT_DOT
     {293, 5}, // 19: exp (MATH_SUB) ->  MATH_SUB value DIR_FROM VARIABLE STMT_DOT
     {293, 5}, // 20: exp (MATH_MULT) ->  MATH_MULT VARIABLE DIR_BY value STMT_DOT
     {293, 5}, // 21: exp (MATH_DIV) ->  MATH_DIV VARIABLE DIR_BY value STMT_DOT
     {293, 1}, // 22: exp ->  struct_while
     {293, 1}, // 23: exp ->  struct_if
     {300, 1}, // 24: value (VARIABLE) ->  VARIABLE
     {300, 1}, // 25: value (NUMBER) ->  NUMBER
     {301, 2}, // 26: to_var (DIR_TO) ->  DIR_TO VARIABLE
     {302, 6}, // 27: struct_while (STRUCT_WHILE) ->  STRUCT_WHILE VARIABLE STMT_DOT expressions STRUCT_ENDWHILE STMT_DOT
     {303, 5}, // 28: struct_if (STRUCT_IF) ->  STRUCT_IF logic_body if_body STRUCT_ENDIF STMT_DOT
     {304, 3}, // 29: logic_body (STMT_DOT) ->  logic_exp STMT_DOT expressions_plus
     {305, 0}, // 30: if_body ->  <empty>
     {305, 1}, // 31: if_body ->  if_else
     {305, 1}, // 32: if_body ->  if_elseif
     {307, 3}, // 33: if_else (STRUCT_ELSE) ->  STRUCT_ELSE STMT_DOT expressions
     {308, 3}, // 34: if_elseif (STRUCT_ELSEIF) ->  STRUCT_ELSEIF logic_body if_elseif
     {308, 2}, // 35: if_elseif (STRUCT_ELSEIF) ->  STRUCT_ELSEIF logic_body
     {308, 3}, // 36: if_elseif (STRUCT_ELSEIF) ->  STRUCT_ELSEIF logic_body if_else
     {306, 2}, // 37: logic_exp ->  value more_logic_exp
     {306, 2}, // 38: logic_exp ->  logic_un_op logic_exp
     {309, 0}, // 39: more_logic_exp ->  <empty>
     {309, 2}, // 40: more_logic_exp ->  logic_bin_op logic_exp
     {310, 1}, // 41: logic_un_op (LOGIC_NOT) ->  LOGIC_NOT
     {311, 1}, // 42: logic_bin_op (LOGIC_AND) ->  LOGIC_AND
     {311, 1}, // 43: logic_bin_op (LOGIC_OR) ->  LOGIC_OR
     {311, 1}, // 44: logic_bin_op (COMP_LS) ->  COMP_LS
     {311, 1}, // 45: logic_bin_op (COMP_GT) ->  COMP_GT
     {311, 1}, // 46: logic_bin_op (COMP_EQ) ->  COMP_EQ
     {312, 1}, // 47: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 4} },             
    { {       289}, { 1} }, // start    
    { {       290}, { 2} }, // prog_decl
    { {       260}, { 3} }, // PROGRAM  
    { {         0}, { 0} },             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, { 16} },                
    { {     291}, {  4} }, // expressions 
    { {     292}, {  5} }, // data_decl   
    { {     293}, {  6} }, // exp         
    { {     261}, {  7} }, // DATA        
    { {     265}, {  8} }, // OP_MOVE     
    { {     266}, {  9} }, // OP_READ     
    { {     268}, { 10} }, // OP_WRITE    
    { {     267}, { 11} }, // OP_ADD      
    { {     283}, { 12} }, // MATH_SUB    
    { {     284}, { 13} }, // MATH_MULT   
    { {     285}, { 14} }, // MATH_DIV    
    { {     302}, { 15} }, // struct_while
    { {     303}, { 16} }, // struct_if   
    { {     273}, { 17} }, // STRUCT_WHILE
    { {     272}, { 18} }, // STRUCT_IF   
    { {       0}, { -2} },                
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       287}, { 19} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_4[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_5[] =
{
    { { REQ_DEF}, { 16} },                
    { {     291}, { 20} }, // expressions 
    { {     292}, {  5} }, // data_decl   
    { {     293}, {  6} }, // exp         
    { {     261}, {  7} }, // DATA        
    { {     265}, {  8} }, // OP_MOVE     
    { {     266}, {  9} }, // OP_READ     
    { {     268}, { 10} }, // OP_WRITE    
    { {     267}, { 11} }, // OP_ADD      
    { {     283}, { 12} }, // MATH_SUB    
    { {     284}, { 13} }, // MATH_MULT   
    { {     285}, { 14} }, // MATH_DIV    
    { {     302}, { 15} }, // struct_while
    { {     303}, { 16} }, // struct_if   
    { {     273}, { 17} }, // STRUCT_WHILE
    { {     272}, { 18} }, // STRUCT_IF   
    { {       0}, { -2} },                
};

SR__ s_6[] =
{
    { { REQ_DEF}, { 16} },                
    { {     291}, { 21} }, // expressions 
    { {     292}, {  5} }, // data_decl   
    { {     293}, {  6} }, // exp         
    { {     261}, {  7} }, // DATA        
    { {     265}, {  8} }, // OP_MOVE     
    { {     266}, {  9} }, // OP_READ     
    { {     268}, { 10} }, // OP_WRITE    
    { {     267}, { 11} }, // OP_ADD      
    { {     283}, { 12} }, // MATH_SUB    
    { {     284}, { 13} }, // MATH_MULT   
    { {     285}, { 14} }, // MATH_DIV    
    { {     302}, { 15} }, // struct_while
    { {     303}, { 16} }, // struct_if   
    { {     273}, { 17} }, // STRUCT_WHILE
    { {     272}, { 18} }, // STRUCT_IF   
    { {       0}, { -2} },                
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       259}, { 22} }, // STMT_OPN
    { {         0}, {  0} },            
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  4} },            
    { {       300}, { 23} }, // value   
    { {       287}, { 24} }, // VARIABLE
    { {       288}, { 25} }, // NUMBER  
    { {         0}, {  0} },            
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       301}, { 26} }, // to_var
    { {       269}, { 27} }, // DIR_TO
    { {         0}, {  0} },          
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  4} },            
    { {       300}, { 28} }, // value   
    { {       287}, { 24} }, // VARIABLE
    { {       288}, { 25} }, // NUMBER  
    { {         0}, {  0} },            
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  4} },            
    { {       300}, { 29} }, // value   
    { {       287}, { 24} }, // VARIABLE
    { {       288}, { 25} }, // NUMBER  
    { {         0}, {  0} },            
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  4} },            
    { {       300}, { 30} }, // value   
    { {       287}, { 24} }, // VARIABLE
    { {       288}, { 25} }, // NUMBER  
    { {         0}, {  0} },            
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       287}, { 31} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       287}, { 32} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       287}, { 33} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  8} },               
    { {       304}, { 34} }, // logic_body 
    { {       306}, { 35} }, // logic_exp  
    { {       300}, { 36} }, // value      
    { {       310}, { 37} }, // logic_un_op
    { {       287}, { 24} }, // VARIABLE   
    { {       288}, { 25} }, // NUMBER     
    { {       286}, { 38} }, // LOGIC_NOT  
    { {         0}, {  0} },               
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 39} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_20[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  6} },                 
    { {       295}, { 40} }, // var_lines    
    { {       296}, { 41} }, // var_line     
    { {       297}, { 42} }, // var_last_line
    { {       298}, { 43} }, // var_line_core
    { {       287}, { 44} }, // VARIABLE     
    { {         0}, {  0} },                 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       301}, { 45} }, // to_var
    { {       269}, { 27} }, // DIR_TO
    { {         0}, {  0} },          
};

SR__ s_24[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 46} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       287}, { 47} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 48} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  3} },          
    { {       301}, { 49} }, // to_var
    { {       269}, { 27} }, // DIR_TO
    { {         0}, {  0} },          
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       271}, { 50} }, // DIR_FROM
    { {         0}, {  0} },            
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       270}, { 51} }, // DIR_BY
    { {         0}, {  0} },          
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       270}, { 52} }, // DIR_BY
    { {         0}, {  0} },          
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 53} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_34[] =
{
    { { REQ_DEF}, {   6} },                 
    { {     305}, {  54} }, // if_body      
    { {     307}, {  55} }, // if_else      
    { {     308}, {  56} }, // if_elseif    
    { {     274}, {  57} }, // STRUCT_ELSE  
    { {     275}, {  58} }, // STRUCT_ELSEIF
    { {       0}, { -30} },                 
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 59} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_36[] =
{
    { { REQ_DEF}, {   8} },                  
    { {     309}, {  60} }, // more_logic_exp
    { {     311}, {  61} }, // logic_bin_op  
    { {     278}, {  62} }, // LOGIC_AND     
    { {     279}, {  63} }, // LOGIC_OR      
    { {     281}, {  64} }, // COMP_LS       
    { {     282}, {  65} }, // COMP_GT       
    { {     280}, {  66} }, // COMP_EQ       
    { {       0}, { -39} },                  
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  7} },               
    { {       306}, { 67} }, // logic_exp  
    { {       300}, { 36} }, // value      
    { {       310}, { 37} }, // logic_un_op
    { {       287}, { 24} }, // VARIABLE   
    { {       288}, { 25} }, // NUMBER     
    { {       286}, { 38} }, // LOGIC_NOT  
    { {         0}, {  0} },               
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -41} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  6} },                 
    { {       295}, { 68} }, // var_lines    
    { {       296}, { 41} }, // var_line     
    { {       297}, { 42} }, // var_last_line
    { {       298}, { 43} }, // var_line_core
    { {       287}, { 44} }, // VARIABLE     
    { {         0}, {  0} },                 
};

SR__ s_42[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       258}, { 69} }, // STMT_COMMA
    { {       257}, { 70} }, // STMT_DOT  
    { {         0}, {  0} },              
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       262}, { 71} }, // TYPE
    { {         0}, {  0} },        
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 72} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 73} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       287}, { 74} }, // VARIABLE
    { {         0}, {  0} },            
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  4} },            
    { {       300}, { 75} }, // value   
    { {       287}, { 24} }, // VARIABLE
    { {       288}, { 25} }, // NUMBER  
    { {         0}, {  0} },            
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  4} },            
    { {       300}, { 76} }, // value   
    { {       287}, { 24} }, // VARIABLE
    { {       288}, { 25} }, // NUMBER  
    { {         0}, {  0} },            
};

SR__ s_53[] =
{
    { { REQ_DEF}, { 16} },                
    { {     291}, { 77} }, // expressions 
    { {     292}, {  5} }, // data_decl   
    { {     293}, {  6} }, // exp         
    { {     261}, {  7} }, // DATA        
    { {     265}, {  8} }, // OP_MOVE     
    { {     266}, {  9} }, // OP_READ     
    { {     268}, { 10} }, // OP_WRITE    
    { {     267}, { 11} }, // OP_ADD      
    { {     283}, { 12} }, // MATH_SUB    
    { {     284}, { 13} }, // MATH_MULT   
    { {     285}, { 14} }, // MATH_DIV    
    { {     302}, { 15} }, // struct_while
    { {     303}, { 16} }, // struct_if   
    { {     273}, { 17} }, // STRUCT_WHILE
    { {     272}, { 18} }, // STRUCT_IF   
    { {       0}, { -2} },                
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       276}, { 78} }, // STRUCT_ENDIF
    { {         0}, {  0} },                
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 79} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, {  8} },               
    { {       304}, { 80} }, // logic_body 
    { {       306}, { 35} }, // logic_exp  
    { {       300}, { 36} }, // value      
    { {       310}, { 37} }, // logic_un_op
    { {       287}, { 24} }, // VARIABLE   
    { {       288}, { 25} }, // NUMBER     
    { {       286}, { 38} }, // LOGIC_NOT  
    { {         0}, {  0} },               
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, { 14} },                    
    { {       294}, { 81} }, // expressions_plus
    { {       293}, { 82} }, // exp             
    { {       265}, {  8} }, // OP_MOVE         
    { {       266}, {  9} }, // OP_READ         
    { {       268}, { 10} }, // OP_WRITE        
    { {       267}, { 11} }, // OP_ADD          
    { {       283}, { 12} }, // MATH_SUB        
    { {       284}, { 13} }, // MATH_MULT       
    { {       285}, { 14} }, // MATH_DIV        
    { {       302}, { 15} }, // struct_while    
    { {       303}, { 16} }, // struct_if       
    { {       273}, { 17} }, // STRUCT_WHILE    
    { {       272}, { 18} }, // STRUCT_IF       
    { {         0}, {  0} },                    
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  7} },               
    { {       306}, { 83} }, // logic_exp  
    { {       300}, { 36} }, // value      
    { {       310}, { 37} }, // logic_un_op
    { {       287}, { 24} }, // VARIABLE   
    { {       288}, { 25} }, // NUMBER     
    { {       286}, { 38} }, // LOGIC_NOT  
    { {         0}, {  0} },               
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_63[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_64[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_65[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_66[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_67[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_68[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_69[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_70[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  4} },                
    { {       299}, { 84} }, // types       
    { {       263}, { 85} }, // TYPE_INTEGER
    { {       264}, { 86} }, // TYPE_BOOLEAN
    { {         0}, {  0} },                
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_73[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 87} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 88} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 89} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  2} },                   
    { {       277}, { 90} }, // STRUCT_ENDWHILE
    { {         0}, {  0} },                   
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 91} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_79[] =
{
    { { REQ_DEF}, { 16} },                
    { {     291}, { 92} }, // expressions 
    { {     292}, {  5} }, // data_decl   
    { {     293}, {  6} }, // exp         
    { {     261}, {  7} }, // DATA        
    { {     265}, {  8} }, // OP_MOVE     
    { {     266}, {  9} }, // OP_READ     
    { {     268}, { 10} }, // OP_WRITE    
    { {     267}, { 11} }, // OP_ADD      
    { {     283}, { 12} }, // MATH_SUB    
    { {     284}, { 13} }, // MATH_MULT   
    { {     285}, { 14} }, // MATH_DIV    
    { {     302}, { 15} }, // struct_while
    { {     303}, { 16} }, // struct_if   
    { {     273}, { 17} }, // STRUCT_WHILE
    { {     272}, { 18} }, // STRUCT_IF   
    { {       0}, { -2} },                
};

SR__ s_80[] =
{
    { { REQ_DEF}, {   5} },                 
    { {     308}, {  93} }, // if_elseif    
    { {     307}, {  94} }, // if_else      
    { {     275}, {  58} }, // STRUCT_ELSEIF
    { {     274}, {  57} }, // STRUCT_ELSE  
    { {       0}, { -35} },                 
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_82[] =
{
    { { REQ_DEF}, { 16} },                
    { {     291}, { 95} }, // expressions 
    { {     292}, {  5} }, // data_decl   
    { {     293}, {  6} }, // exp         
    { {     261}, {  7} }, // DATA        
    { {     265}, {  8} }, // OP_MOVE     
    { {     266}, {  9} }, // OP_READ     
    { {     268}, { 10} }, // OP_WRITE    
    { {     267}, { 11} }, // OP_ADD      
    { {     283}, { 12} }, // MATH_SUB    
    { {     284}, { 13} }, // MATH_MULT   
    { {     285}, { 14} }, // MATH_DIV    
    { {     302}, { 15} }, // struct_while
    { {     303}, { 16} }, // struct_if   
    { {     273}, { 17} }, // STRUCT_WHILE
    { {     272}, { 18} }, // STRUCT_IF   
    { {       0}, { -2} },                
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_85[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_86[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       257}, { 96} }, // STMT_DOT
    { {         0}, {  0} },            
};

SR__ s_91[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_92[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_95[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

// $insert defaultactionreturn
                            // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 41 "abaps.y"
        {
         std::cout << "start -> prog_decl expressions" << std::endl;
         }
        break;

        case 2:
#line 48 "abaps.y"
        {
         std::cout << "expressions -> null" << std::endl;
         }
        break;

        case 3:
#line 53 "abaps.y"
        {
         std::cout << "expressions -> data_decl expressions" << std::endl;
         }
        break;

        case 4:
#line 58 "abaps.y"
        {
         std::cout << "expressions -> exp expressions" << std::endl;
         }
        break;

        case 5:
#line 65 "abaps.y"
        {
         std::cout << "expressions_plus -> exp expressions" << std::endl;
         }
        break;

        case 6:
#line 72 "abaps.y"
        {
         std::cout << "prog_decl -> PROGRAM VARIABLE STMT_DOT" << std::endl;
         }
        break;

        case 7:
#line 79 "abaps.y"
        {
         std::cout << "data_decl -> DATA_STMT_OPN var_lines" << std::endl;
         }
        break;

        case 8:
#line 86 "abaps.y"
        {
         std::cout << "var_lines -> var_line var_lines" << std::endl;
         }
        break;

        case 9:
#line 91 "abaps.y"
        {
         std::cout << "var_line -> var_last_line" << std::endl;
         }
        break;

        case 10:
#line 98 "abaps.y"
        {
         std::cout << "var_line -> VARIABLE TYPE types" << std::endl;
         }
        break;

        case 11:
#line 105 "abaps.y"
        {
         std::cout << "var_line -> var_line_core STMT_COMMA" << std::endl;
         }
        break;

        case 12:
#line 112 "abaps.y"
        {
         std::cout << "var_last_line -> var_line_core STMT_DOT" << std::endl;
         }
        break;

        case 13:
#line 119 "abaps.y"
        {
         std::cout << "types -> TYPE_INTEGER" << std::endl;
         }
        break;

        case 14:
#line 124 "abaps.y"
        {
         std::cout << "types -> TYPE_BOOLEAN" << std::endl;
         }
        break;

        case 15:
#line 131 "abaps.y"
        {
         std::cout << "exp -> OP_MOVE value to_var STMT_DOT" << std::endl;
         }
        break;

        case 16:
#line 136 "abaps.y"
        {
         std::cout << "exp -> OP_READ to_var STMT_DOT" << std::endl;
         }
        break;

        case 17:
#line 141 "abaps.y"
        {
         std::cout << "exp -> OP_WRITE VARIABLE STMT_DOT" << std::endl;
         }
        break;

        case 18:
#line 146 "abaps.y"
        {
         std::cout << "exp -> OP_ADD value to_var STMT_DOT" << std::endl;
         }
        break;

        case 19:
#line 151 "abaps.y"
        {
         std::cout << "exp -> MATH_SUB value DIR_FROM VARIABLE STMT_DOT" << std::endl;
         }
        break;

        case 20:
#line 156 "abaps.y"
        {
         std::cout << "exp -> MATH_MULT VARIABLE DIR_BY value STMT_DOT" << std::endl;
         }
        break;

        case 21:
#line 161 "abaps.y"
        {
         std::cout << "exp -> MATH_DIV VARIABLE DIR_BY value STMT_DOT" << std::endl;
         }
        break;

        case 22:
#line 166 "abaps.y"
        {
         std::cout << "exp -> struct_while" << std::endl;
         }
        break;

        case 23:
#line 171 "abaps.y"
        {
         std::cout << "exp -> struct_if" << std::endl;
         }
        break;

        case 24:
#line 178 "abaps.y"
        {
         std::cout << "value -> VARIABLE" << std::endl;
         }
        break;

        case 25:
#line 183 "abaps.y"
        {
         std::cout << "value -> NUMBER" << std::endl;
         }
        break;

        case 26:
#line 190 "abaps.y"
        {
         std::cout << "to_var -> DIR_TO variable" << std::endl;
         }
        break;

        case 27:
#line 197 "abaps.y"
        {
         std::cout << "while -> STRUCT_WHILE exp STMT_DOT expressions STRUCT_ENDWHILE STMT_DOT" << std::endl;
         }
        break;

        case 28:
#line 204 "abaps.y"
        {
         std::cout << "struct_if -> STRUCT_IF logic_body if_body STRUCT_ENDIF STMT_DOT" << std::endl;
         }
        break;

        case 29:
#line 211 "abaps.y"
        {
         std::cout << "logic_body -> logic_exp STMT_DOT expressions_plus" << std::endl;
         }
        break;

        case 30:
#line 218 "abaps.y"
        {
         std::cout << "if_body -> null" << std::endl;
         }
        break;

        case 31:
#line 223 "abaps.y"
        {
         std::cout << "if_body -> if_else" << std::endl;
         }
        break;

        case 32:
#line 228 "abaps.y"
        {
         std::cout << "if_body -> if_elseif" << std::endl;
         }
        break;

        case 33:
#line 235 "abaps.y"
        {
         std::cout << "if_else -> STRUCT_ELSE STMT_DOT expressions" << std::endl;
         }
        break;

        case 34:
#line 242 "abaps.y"
        {
         std::cout << "if_elseif -> STRUCT_ELSEIF logic_body if_elseif" << std::endl;
         }
        break;

        case 35:
#line 247 "abaps.y"
        {
         std::cout << "if_elseif -> STRUCT_ELSEIF logic_body" << std::endl;
         }
        break;

        case 36:
#line 252 "abaps.y"
        {
         std::cout << "if_elseif -> STRUCT_ELSEIF logic_body if_else" << std::endl;
         }
        break;

        case 37:
#line 259 "abaps.y"
        {
         std::cout << "logic_exp -> value more_logic_exp" << std::endl;
         }
        break;

        case 38:
#line 264 "abaps.y"
        {
         std::cout << "logic_exp -> logic_un_op logic_exp" << std::endl;
         }
        break;

        case 39:
#line 271 "abaps.y"
        {
         std::cout << "more_logic_exp -> null" << std::endl;
         }
        break;

        case 40:
#line 276 "abaps.y"
        {
         std::cout << "more_logic_exp -> logic_bin_op logic_exp" << std::endl;
         }
        break;

        case 41:
#line 283 "abaps.y"
        {
         std::cout << "logic_un_op -> LOGIC_NOT" << std::endl;
         }
        break;

        case 42:
#line 290 "abaps.y"
        {
         std::cout << "logic_bin_op -> LOGIC_AND" << std::endl;
         }
        break;

        case 43:
#line 295 "abaps.y"
        {
         std::cout << "logic_bin_op -> LOGIC_OR" << std::endl;
         }
        break;

        case 44:
#line 300 "abaps.y"
        {
         std::cout << "logic_bin_op -> COMP_LS" << std::endl;
         }
        break;

        case 45:
#line 305 "abaps.y"
        {
         std::cout << "logic_bin_op -> COMP_GT" << std::endl;
         }
        break;

        case 46:
#line 310 "abaps.y"
        {
         std::cout << "logic_bin_op -> COMP_EQ" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



